config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  get "requests/index"

  get "requests/show"

  resources :projects do
    resources :alerts
    match '/metrics' => 'projects#metrics', via: :get
    member do
      match 'page_load_last_100' => 'projects#page_load_last_100', via: :get
      match 'rpm' => 'projects#rpm', via: :get
      match 'memory' => 'projects#memory', via: :get
      match 'page_load' => 'projects#page_load', via: :get
    end
    resources :requests, only: [:index, :show] do
      collection do
        get :dashboard
        get :busiest_paths
      end
    end
    resources :users, only: [:index, :destroy]
    resources :invitations
  end
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  namespace :api do
    namespace :v1 do
      match '/' => 'projects#index', via: :post, defaults: {format: :json}
    end
  end

  root 'projects#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :owned_projects, class_name: 'Project', foreign_key: :owner_id
  has_and_belongs_to_many :projects
  validates_presence_of :name
  validates_inclusion_of :time_zone, in: ActiveSupport::TimeZone.zones_map.keys
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_project

  def index
    @users = @project.users.all
    @invitation = Invitation.new
  end

  def destroy
    @project.users.delete(@project.users.find(params[:id]))
    redirect_to project_users_path(@project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end
end

app/views/users/index.html.erb
<div class="container">
  <h1>Members of <%= @project.name %></h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'projects/subnav' %>
    </div>
    <div class="col-md-9">
      <table class="table table-condensed table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>

        <tbody>
          <% @project.users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to 'Remove', project_user_path(@project, user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <fieldset>
        <legend>Invite someone</legend>
        <%= render 'invitations/form' %>
      </fieldset>

      <table class="table table-condensed table-bordered append">
        <thead>
          <tr>
            <th>Email</th>
            <th>Sent at</th>
          </tr>
        </thead>

        <tbody>
          <% @project.invitations(persisted: true).each do |invitation| %>
            <tr>
              <td><%= invitation.email %></td>
              <td><%= invitation.created_at %></td>
              <td>
                <%= link_to 'Revoke', project_invitation_path(@project, invitation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>

    </div>
  </div>
</div>