config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  get "requests/index"

  get "requests/show"

  resources :projects do
    resources :alerts
    match '/metrics' => 'projects#metrics', via: :get
    member do
      match 'page_load_last_100' => 'projects#page_load_last_100', via: :get
      match 'rpm' => 'projects#rpm', via: :get
      match 'memory' => 'projects#memory', via: :get
      match 'page_load' => 'projects#page_load', via: :get
    end
    resources :requests, only: [:index, :show] do
      collection do
        get :dashboard
        get :busiest_paths
      end
    end
    resources :users, only: [:index, :destroy]
    resources :invitations
  end
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  namespace :api do
    namespace :v1 do
      match '/' => 'projects#index', via: :post, defaults: {format: :json}
    end
  end

  root 'projects#index'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  validate :email_cannot_be_owners
  before_save :generate_token
  before_save :set_user_id
  validate :email_cannot_be_owners

  def email_cannot_be_owners
    errors.add(:email, "can't be yours") if self.email == self.project.owner.email
  end

  def set_user_id
    user = User.where(email: email).first
    self.user_id = user.id unless user.nil?
  end

  def generate_token
    self.token = SecureRandom.hex
  end
end

app/controllers/invitation_controller.rb
class InvitationController < Devise::RegistrationsController
  layout 'login'
  def invitation
    @invitation = Invitation.where(token: params[:invitation][:token]).first
    if @invitation.nil?
      flash[:alert] = 'Invalid token'
      redirect_to root_url
      return
    end
    unless @invitation.user.nil?
      @invitation.project.users<< @invitation.user unless @invitation.project.users.include? @invitation.user
      @invitation.destroy
      redirect_to new_user_session_path
    end
    @user = User.new(email: @invitation.email)
  end

  def register_invitation
    @invitation = Invitation.where(token: params[:invitation][:token]).first
    @user = User.new user_params
    @user.email = @invitation.email
    if @user.save
      if @user.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(:user, @user)
        @invitation.project.users<< @user
        @invitation.destroy
        respond_with @user, :location => after_sign_up_path_for(@user)
      else
        set_flash_message :notice, :"signed_up_but_#{@user.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with @user, :location => after_inactive_sign_up_path_for(@user)
      end
    else
      render :invitation
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_project
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = @project.invitations.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = @project.invitations.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html {
          InvitationMailer.invite(@invitation).deliver
          redirect_to project_users_path(@project), notice: 'Invitation was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @invitation }
      else
        format.html { render 'users/index' }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to project_invitations_path(@project), notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to project_users_path(@project) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = @project.invitations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:email)
    end
end

app/views/invitations/_form.html.erb
<%= simple_form_for([@project, @invitation], html: {class: 'form-inline'}) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <%= f.submit 'Send invitation', class: 'btn btn-primary' %>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>