config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  get "requests/index"

  get "requests/show"

  resources :projects do
    resources :alerts
    match '/metrics' => 'projects#metrics', via: :get
    member do
      match 'page_load_last_100' => 'projects#page_load_last_100', via: :get
      match 'rpm' => 'projects#rpm', via: :get
      match 'memory' => 'projects#memory', via: :get
      match 'page_load' => 'projects#page_load', via: :get
    end
    resources :requests, only: [:index, :show] do
      collection do
        get :dashboard
        get :busiest_paths
      end
    end
    resources :users, only: [:index, :destroy]
    resources :invitations
  end
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  namespace :api do
    namespace :v1 do
      match '/' => 'projects#index', via: :post, defaults: {format: :json}
    end
  end

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :requests
  has_many :invitations
  has_many :alerts, dependent: :destroy
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_and_belongs_to_many :users
  after_create -> { self.users<<(self.owner) }
  after_create :reset_api_key

  def reset_api_key
    update_attribute :api_key, SecureRandom.hex if api_key.blank?
  end

  def storage_size
    size = 0
    %w{requests renders queries}.each do |table|
      size =+ ActiveRecord::Base.connection.execute("SELECT sum(pg_column_size(#{table})) FROM #{table} where project_id = #{self.id};")[0]["sum"].to_i
    end
    size
  end

  def requests_today
    requests.where('started > ?', DateTime.now.beginning_of_day).count
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ActionController::Base
  respond_to :json

  def index
    head :bad_request  and return if params[:api_version].nil? or params[:api_key].nil? or params[:data].nil?
    project = Project.where(api_key: params[:api_key]).first
    request = ApiRequest.create(project_id: project.id, api_version: params[:api_version], data: params[:data])
    RequestWorker.perform_async(request.id)
    head :ok
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  skip_load_resource only: [:create]
  def metrics
    @project = current_user.projects.find(params[:project_id])
    @filter = Filter.new(params[:filter])
    respond_to do |format|
      format.html {}
      format.json{
        data = {}
        diff = ((@filter.to_time - @filter.from_time) / 3600).round.abs
        step = diff.minutes

        points = points(@filter.from_time, @filter.to_time, step)
        format = (diff <= 24) ? :time : :short
        format = :short
        @rpm = {}
        result = @project.requests.where(started: @filter.from_time...@filter.to_time, env: @filter.env).group_by(step).count
        result.each do |i, e|
          @rpm[Time.at(i*step)] = e
        end
        @rpm = Hash[@rpm.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}.sort]
        @rpm = points.merge(@rpm)
        @rpm = Hash[@rpm.inject({}){|memo,(k,v)| memo[k] = v; memo}.sort]

        @response_time = {}
        values = []
        @project.requests.where(started: @filter.from_time...@filter.to_time, env: @filter.env).group_by(step).average(:duration).each do |i, e|
          @response_time[Time.at(i*step)] = e
        end
        @response_time = Hash[@response_time.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}.sort]
        @response_time = points.merge(@response_time)
        @response_time = Hash[@response_time.inject({}){|memo,(k,v)| memo[k] = v.to_f.round; memo}.sort]

        @response_time_2 = {}
        h = {}
        @project.requests.select("percentile_95th(duration) as duration, round(extract(epoch from \"started\"::timestamptz AT TIME ZONE 'Etc/UTC')/#{step}) AS timestamp").where(started: @filter.from_time...@filter.to_time, env: @filter.env).group_by(step).map{|r| h[r.timestamp] = r.duration }
        h.each do |i, e|
          @response_time_2[Time.at(i*step)] = e
        end
        @response_time_2 = Hash[@response_time_2.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}.sort]
        @response_time_2 = points.merge(@response_time_2)
        @response_time_2 = Hash[@response_time_2.inject({}){|memo,(k,v)| memo[k] = v.to_f.round; memo}.sort]

        @memory = {}
        @project.requests.where(started: @filter.from_time...@filter.to_time, env: @filter.env).group_by(step).average(:memory).each do |i, e|
          @memory[Time.at(i*step)] = e
        end
        @memory = @memory.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}
        @memory = points.merge(@memory)
        @memory = Hash[@memory.inject({}){|memo,(k,v)| memo[k] = v.to_f.round; memo}.sort]

        data[:response_time] = [{
          key: 'Response time',
          color: '#75BE23',
          values: @response_time.map{|i, v| {x: i.to_i.in_milliseconds, y: v }},
          area: true
        }]

        data[:response_time_2] = [{
          key: 'Response time 2',
          color: '#75BE23',
          values: @response_time_2.map{|i, v| {x: i.to_i.in_milliseconds, y: v }},
          area: true
        }]

        data[:rpm] = [{
          key: 'Requests per minute',
          color: '#75BE23',
          values: @rpm.map{|i, v| {x: i.to_i.in_milliseconds, y: v}},
          area: true
        }]

        data[:memory] = [{
          key: 'Memory usage(MB)',
          color: '#75BE23',
          values: @memory.map{|i, v| {x: i.to_i.in_milliseconds, y: v}},
          area: true
        }]
        render json: data
      }
    end
  end

  def page_load_last_100
    @requests = @project.requests.order('created_at desc').limit(100).all.reverse
    data = @requests.map do |request|
      [
        request.started.to_s(:short),
        request.db_runtime.round(2),
        request.duration.round(2),
        render_to_string(partial: 'tooltip', locals: {request: request}, formats: [:html])
      ]
    end
    render json: data
  end

  def rpm
    @rpm = @project.requests.where(started: 30.minutes.ago...Time.now).group_by_minute(:started).count()
    @rpm = @rpm.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}
    @rpm = points.merge(@rpm)
    @rpm = Hash[@rpm.inject({}){|memo,(k,v)| memo[k.change(sec: '00').to_s(:time)] = v; memo}.sort]
    data = [["Time", "RPM"]]
    data = data.concat(@rpm.to_a)
    render json: data
  end

  def memory
    @memory = @project.requests.where(started: 30.minutes.ago...Time.now).group_by_minute(:started).average(:memory)
    @memory = @memory.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}
    @memory = points.merge(@memory)
    @memory = Hash[@memory.inject({}){|memo,(k,v)| memo[k.change(sec: '00').to_s(:time)] = v; memo}.sort]
    data = [["Time", "Memory"]]
    data = data.concat(@memory.to_a)
    render json: data
  end

  def page_load
    @response_time = @project.requests.where(started: 30.minutes.ago...Time.now).group_by_minute(:started).average(:duration)
    @response_time = @response_time.inject({}){|memo,(k,v)| memo[k.change(sec: '00')] = v; memo}
    @response_time = points.merge(@response_time)
    @response_time = Hash[@response_time.inject({}){|memo,(k,v)| memo[k.change(sec: '00').to_s(:time)] = v; memo}.sort]
    data = [["Time", "Average response time"]]
    data = data.concat(@response_time.to_a)
    render json: data
  end
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = current_user.projects.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.owned_projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.owned_projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end

    def points(from, to, step)
      points = {}
      while to > from do
        points[from] = 0
        from += step
      end
      points
    end

  def can_view_metrics?
    current_user == @project.owner || @project.users.include?(current_user)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/projects/_subnav.html.erb
<ul class="nav nav-tabs nav-stacked">
  <li><%= link_to 'Project', edit_project_path(@project), class: '' %></li>
  <li><%= link_to 'Alerts', project_alerts_path(@project), class: '' %></li>
  <li><%= link_to 'Members', project_users_path(@project), class: '' %></li>
</ul>

app/views/projects/_tooltip.html.erb
<div class="chart-tooltip">
	<strong><%= "#{request.method} #{request.path}" %></strong><br />
	<%= "#{request.duration}ms at #{request.started.to_s(:short)}" %><br />
	<%= link_to 'View details', project_request_path(request.project, request), class: 'btn btn-mini', target: '_blank', data: { toggle: "modal", target: "#ajax-modal"} %>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Editing project</h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'subnav' %>
    </div>
    <div class="col-md-9">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projects</h1>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>API key</th>
        <th>Requests today</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.api_key %></td>
          <td><%= project.requests_today %></td>
          <td>
            <%= link_to 'Metrics', project_metrics_path(project), class: 'btn btn-small btn-primary' %>
            <%= link_to 'Settings', edit_project_path(project), class: 'btn btn-small btn-default' %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' if current_user == project.owner %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add Project', new_project_path, class: 'btn btn-primary' %>
</div>

app/views/projects/metrics.html.erb
<div class="container-fluid">
  <h1><%= @project.name %></h1>
  <%= render_navigation(context: :project) %>
  <div class="append clearfix"></div>
  <a href="#" class="btn btn-default btn-lg" onclick="introJs().setOptions({ 'tooltipPosition': 'top' }).start();"><span class="fa fa-question-circle"></span> Help</a>

  <div id="filter" data-intro="You can filter the results by daterange.">
    <%= form_for @filter, url: project_metrics_path(@project),html: {class: 'form form-inline', method: :get, id: 'filter-form'} do |f| %>
      <%= f.label "From:"%> <%= f.text_field :from, class: 'datetimepicker' %> <%= f.label "To:"%> <%= f.text_field :to, class: 'datetimepicker' %> <%= f.label "Environment:"%> <%= f.select :env, [["Production", "production"], ["Development", "development"], ["Staging", "staging"]] %>
      <%= f.button "Submit", class: 'btn btn-xs btn-default' %>
    <% end %>
  </div>

  <div class="append">
    <%= link_to "< 1 hour", project_metrics_path(@project, filter: {from: Time.parse(@filter.from).ago(1.hour).strftime("%Y-%m-%d %H:%M"), to: @filter.from}), class: 'btn btn-sm btn-default' %>
    <%= link_to("1 hour >", project_metrics_path(@project, filter: {from: @filter.to, to: Time.parse(@filter.to).advance(hours: 1).strftime("%Y-%m-%d %H:%M")}), class: 'btn btn-sm btn-default float-right') if @filter.to_time < Time.current %>
  </div>

  <div class="row append">
    <div class="col-md-12 box" data-intro="You can view the average response time here. The graph periodically updates itself if you are not filtering for a date range.">
      <div class="header"><strong>Average</strong> response time(ms)</div>
      <div id="response_time" class="chart">
        <svg></svg>
      </div>
    </div>
  </div>

  <div class="row append">
    <div class="col-md-12 box" data-intro="You can view the average response time here. The graph periodically updates itself if you are not filtering for a date range.">
      <div class="header"><strong>95th percentile</strong> response time(ms)</div>
      <div id="response_time_2" class="chart">
        <svg></svg>
      </div>
    </div>
  </div>

  <div class="row append" data-intro="This is a similar list to the above one but for the average throughput.">
    <div class="col-md-12 box">
      <div class="header"><strong>Average</strong> throughput</div>
      <div id="rpm" class="chart">
        <svg></svg>
      </div>
    </div>
  </div>

  <div class="row append" data-intro="The average memory used by the requests. We only collect this data when a request been made hence the zero values.">
    <div class="col-md-12 box">
        <div class="header"><strong>Average</strong> memory usage(MB)</div>
        <div id="memory" class="chart">
          <svg></svg>
        </div>
    </div>
  </div>

  <div id="requests">
    <div class="row append">
        <div class="col-md-6 box" data-intro="The top 10 slowest request. You can click on the bar to view the details.">
          <div class="header">Slowest response time (last 7 days)</div>
          <div id="slow" class="chart">
            <svg></svg>
          </div>
        </div>
        <div class="col-md-6 box" data-intro="Top 10 busiest URLs in your app.">
          <div class="header">Highest throughput (last 7 days)</div>
          <div id="highest_throughput" class="chart">
            <svg></svg>
          </div>
        </div>
    </div>
    <div class="clearfix append"></div>
    <%= link_to 'All requests', project_requests_path(@project), class: 'btn btn-default' %>
  </div>
</div>
<script type="text/javascript">
  d3_charts();
  $.get('<%= dashboard_project_requests_path(@project.id, format: :json) %>', function(data){
    horizontal_bar(data['slowest'], '#slow svg')
    horizontal_bar(data['highest_throughput'], '#highest_throughput svg')
  })
  $(".datetimepicker").datetimepicker({
    dateFormat: 'yy-mm-dd', timeFormat: 'HH:mm', maxDate: '+0m', maxDateTime: new Date(),
    beforeShow: function (textbox, instance) {
      instance.dpDiv.css({
        marginTop: '60px',
      });
    }
  });
</script>
<div id="ajax-modal" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header no-border">
        <strong>Request details</strong>
        <a class="close" data-dismiss=modal>&times;</a>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h1>New project</h1>
  <%= render 'form' %>
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <h1>Project details</h1>

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @project.name %>
  </p>

  <p>
    <strong>Api key:</strong>
    <%= @project.api_key %>
  </p>
  <div id="usage" class="chart">
    <svg></svg>
  </div>
  <%= link_to 'Back', projects_path, class: 'btn' %>
</div>
<script>
  var chart = line_chart('Daily requests')
  var data = [{
    key: 'Daily requests',
    color: '#75BE23',
    values: <%== @project.requests.group_by_day(:created_at).count.map{|i, v| {x: i.to_i * 1000, y: v}}.sort_by{|k, v| k[:x]}.to_json %>,
    area: true
  }]
  d3line(data, "#usage svg", chart)
</script>