config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  get "requests/index"

  get "requests/show"

  resources :projects do
    resources :alerts
    match '/metrics' => 'projects#metrics', via: :get
    member do
      match 'page_load_last_100' => 'projects#page_load_last_100', via: :get
      match 'rpm' => 'projects#rpm', via: :get
      match 'memory' => 'projects#memory', via: :get
      match 'page_load' => 'projects#page_load', via: :get
    end
    resources :requests, only: [:index, :show] do
      collection do
        get :dashboard
        get :busiest_paths
      end
    end
    resources :users, only: [:index, :destroy]
    resources :invitations
  end
  devise_for :users, :skip => [:registrations]
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  namespace :api do
    namespace :v1 do
      match '/' => 'projects#index', via: :post, defaults: {format: :json}
    end
  end

  root 'projects#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :project
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_project
  before_action :set_alert, only: [:show, :edit, :update, :destroy]
  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = @project.alerts.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = @project.alerts.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to project_alerts_url(@project), notice: 'Alert was successfully created.' }
        format.json { render action: 'show', status: :created, location: @alert }
      else
        format.html { render action: 'new' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to project_alerts_url(@project), notice: 'Alert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to project_alerts_url(@project) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.owned_projects.find(params[:project_id])
    end
    def set_alert
      @alert = @project.alerts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:project_id, :active, :response_time_treshold)
    end
end

app/views/alerts/_form.html.erb
<%= form_for([@project, @alert], html: {class: 'form-horizontal'}) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :active %> Active
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :response_time_treshold, class: 'col-sm-2 control-label' %>
    <%= f.number_field :response_time_treshold %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/alerts/edit.html.erb
<div class="container">
  <h1>Edit alert for <%= @project.name %></h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'projects/subnav' %>
    </div>
    <div class="col-md-9">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/alerts/index.html.erb
<div class="container">
  <h1>Alerts of <%= @project.name %></h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'projects/subnav' %>
    </div>
    <div class="col-md-9">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>Active</th>
            <th>Response time treshold (ms)</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @alerts.each do |alert| %>
            <tr>
              <td><%= alert.active %></td>
              <td><%= alert.response_time_treshold %></td>
              <td>
                <%= link_to 'Edit', edit_project_alert_path(@project, alert), class: 'btn btn-default btn-mini' %>
                <%= link_to 'Destroy', project_alert_path(@project, alert), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Alert', new_project_alert_path(@project), class: 'btn btn-primary' %>

    </div>
  </div>
</div>

app/views/alerts/new.html.erb
<div class="container">
  <h1>New alert for <%= @project.name %></h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'projects/subnav' %>
    </div>
    <div class="col-md-9">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @alert.project %>
</p>

<p>
  <strong>Active:</strong>
  <%= @alert.active %>
</p>

<p>
  <strong>Response time treshold:</strong>
  <%= @alert.response_time_treshold %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>